[package]
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
name = "sp2-lammps-wrap"
version = "0.1.0"

[lib]
path = "lib.rs"

[dependencies]
log = "0.3"
ndarray = "0.10.6"
lammps-sys = { path = "../lammps-sys" }
sp2-slice-of-array = { path = "../util/slice-of-array" }
