[package]
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
name = "sp2-lammps-wrap"
version = "0.1.0"

[dependencies]
log = "0.3"
ndarray = "0.10.6"
lammps-sys = { path = "../lammps-sys" }
sp2-array-utils = { path = "../util/array" }