---
potential:
  - lammps:
      reaxff: {}
scale-ranges:
  repeat-count: 2
  scalables:
    - parameter:
        axis-mask:
          - 1
          - 1
          - 0
        guess: 3.17
        range:
          - 3
          - 3.20
    - layer-seps:
        guess: 6
        range:
          - 5
          - 8
        mask:
          - 0
          - 0
          - 1
          - 0
          - 0
cg:
  stop-condition:
    grad-max: .0002
ev-loop:
  min-positive-iter: 1
  max-iter: 3
  fail: false
ev-chase:
  cg:
    stop-condition:
      any:
        - value-delta:
            rel-greater-than: 0
            steps-ago: 10
        - iterations: 100
threading: rayon
phonons:
  supercell:
    target:
      - 35
      - 35
      - 0
  disp-finder: 
    rsp2: {}
  eigensolver:
    dense: {}
  symmetry-tolerance: 0.001
  displacement-distance: 0.0001
parameters:
  - a
  - a
  - ~
animate: {}
layer-gamma-threshold: 0.2
bond-radius: 1.8
