[package]
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
name = "sp2-kets"
version = "0.1.0"

[lib]
path = "lib.rs"

[dependencies]
lazy_static = "0.2.8"
serde = "1.0.8"
serde_derive = "1.0.8"
