[package]
name = "sp2-structure"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]

[lib]
path = "lib.rs"

[dependencies]
ordered-float = "0.5"
sp2-array-utils = {path = "../array"}