potential:
  supercell: {target: [1, 1, 1]}
scale-ranges:
  parameter:
    guess: 2.46
    range: [2.38, 2.54]
  layer-sep:
    guess: 3.38
    range: [3.25, 3.45]
cg:
  stop-condition:
    any:
      - value-delta:
          rel-greater-than: 0
          steps-ago: 10
      - iterations: 100
  alpha-guess-max: 1e-1
  alpha-guess-first: 1e-2
ev-chase: one-by-one
threading: lammps
phonons:
  supercell: {target: [35, 35, 1]}
  symmetry-tolerance: 1e-2
  displacement-distance: 1e-4
