supercell-relax: {target: [35, 35, 1]}
supercell-phonopy: {target: [35, 35, 1]}
# coarse linear search gives this for all AB structures
hack-scale:
 - 0.9833333333333333
 - 0.9833333333333333
 - 1
displacement-distance: 1e-4
neg-frequency-threshold: 1e-3
# neg-frequency-threshold: 1e-3
cg:
  stop-condition:
    any:
      - grad-rms: 1e-14
      #- all:
        #- grad-rms: 1e-9
      - iterations: 100
      #- iterations: 1
  alpha-guess-max: 1e-1
  alpha-guess-first: 1e-2
