potential:
  supercell: {target: [1, 1, 1]}
# coarse linear search gives this for all AB structures
hack-scale:
 - 0.9833333333333333
 - 0.9833333333333333
 - 1
cg:
  stop-condition:
    any:
      - value-delta:
          rel-greater-than: 0
          steps-ago: 10
      - iterations: 100
  alpha-guess-max: 1e-1
  alpha-guess-first: 1e-2
ev-chase: one-by-one
threading: lammps
phonons:
  supercell: {target: [35, 35, 1]}
  symmetry-tolerance: 1e-2
  displacement-distance: 1e-4
