[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "Function minimization algorithms, even in multiple dimensions."
!!LICENSE-PERMISSIVE

[dependencies]
!!itertools
!!log
!!ordered-float
!!rand
!!serde
!!serde_derive
!!serde_json
!!either

!!rsp2-array-utils
!!rsp2-assert-close
!!rsp2-slice-math
!!rsp2-util-macros

!!failure

# FIXME make this dev-dependencies once rust-lang-nursery/rls#169 is fixed
# FIXME use fern for less hax?
!!env-logger

[features]
!!NIGHTLY-FEATURE-LINE
