[package]
name = "rsp2-structure"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-array-utils
!!rsp2-assert-close

!!error-chain
!!slice-of-array
!!ordered-float
!!itertools
!!lazy-static
!!log

!!rand
