[package]
name = "rsp2-array-utils"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]

[lib]
path = "lib.rs"

[dependencies]
# HACK: These are public dependencies of rsp2-array-types and shouldn't be here
!!serde
!!serde-derive
!!slice-of-array

!!rsp2-assert-close

[dev-dependencies]
!!rand
