[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]

# Note: The majority of subcrates are dual-licensed under MIT or Apache 2.0,
#       but the project as a whole is provided under the GPL.
#       Please refer to individual subcrate Cargo.tomls and source file headers.
!!LICENSE-GPL

!!BINARY-SHIM-BIN-ENTRIES

[dependencies]

# Workspace members
!!WORKSPACE-MEMBERS-AS-PATH-DEPS

# Deps of examples/ and tests/.
# Some of these could be dev-dependencies, however currently
#  none of them are due to rust-lang-nursery/rls#169
!!rand
!!serde_json
!!serde_yaml
!!log
!!fern
!!env-logger
!!clap
!!rsp2-kets
!!slice-of-array
!!ansi-term
!!itertools
!!failure
!!path-abs
!!serde
!!serde-derive
!!pretty-assertions
!!mpi { optional = true }

!!libffi-sys { features = ["system"] }

[features]
default = ["mpi-support"]

# Used by integration tests to make them show nice diffs using pretty_assertions.
#
# see doc/updating-tests.md for more details
test-diff=["rsp2-integration-test/test-diff"]

# FIXME
# Features for optional deps, because the implicit features defined by deps do not scale well.
# For now, THESE are what you should toggle in dependent crates.
#
# Once namespaced-features are stabilized, these features will be renamed after the deps.
# see https://github.com/rust-lang/cargo/issues/1286 (problem and proposal)
#     https://github.com/rust-lang/cargo/issues/5565 (tracking issue, of sorts)
mpi-support = ["mpi", "rsp2-tasks/mpi-support"]

!!NIGHTLY-FEATURE-LINE

!!MAYBE-ITS-A-WORKSPACE

[patch.crates-io.libffi-sys]

# version = "0.6.2-alpha.0"
git = "https://github.com/ExpHP/libffi-sys-rs"
branch = "system-feature-patchable"
#rev = "11238e18"
