[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "Provides safe abstractions for moving data out of arrays."

[lib]
path = "lib.rs"

[dependencies]
