[package]
name = "rsp2-tasks"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-lammps-wrap
!!rsp2-minimize
!!rsp2-structure
!!rsp2-structure-io
!!rsp2-phonopy-io
!!rsp2-array-utils
!!rsp2-slice-math
!!rsp2-tempdir
!!rsp2-util-macros
!!rsp2-eigenvector-classify

!!slice-of-array
!!rsp2-kets
!!serde
!!serde_json
!!serde_derive
!!rand
!!log
!!env_logger
!!itertools
!!ansi-term
