[package]
name = "rsp2-phonopy-io"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "Parses/writes some of phonopy's filetypes.  And some of rsp2's own made-up filetypes used around phonopy. Not sure why this exists really. Maybe to save `rsp2-tasks` some compile time?"

[lib]
path = "lib.rs"

[dependencies]
!!error-chain
!!nom
!!serde
!!serde-derive
!!serde-yaml
!!serde-json
!!byte-tools

!!rsp2-structure
!!rsp2-array-types

!!rsp2-kets
