[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]

!!BINARY-SHIM-BIN-ENTRIES

[dependencies]

# Workspace members
!!WORKSPACE-MEMBERS-AS-PATH-DEPS

# Deps of examples/ and tests/.
# Some of these could be dev-dependencies, however currently
#  none of them are due to rust-lang-nursery/rls#169
!!rand
!!serde_json
!!serde_yaml
!!log
!!fern
!!env-logger
!!clap
!!rsp2-kets
!!slice-of-array
!!ansi-term
!!itertools
!!failure
!!path-abs
!!serde
!!serde-derive
!!pretty-assertions

[features]
# Used by integration tests to make them show nice diffs using pretty_assertions.
#
# see doc/updating-tests.md for more details
test-diff=["rsp2-integration-test/test-diff"]

!!NIGHTLY-FEATURE-LINE

!!MAYBE-ITS-A-WORKSPACE
