[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "A safe(r) wrapper around the lammps C bindings."
!!LICENSE-GPL

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-structure
!!rsp2-array-types
!!lammps-sys

!!log
!!lazy-static
!!chrono
!!failure
!!slice-of-array

# FIXME: should be an optional dependency, but the crates script
#        has no way to do that.
!!mpi

[features]
!!NIGHTLY-FEATURE-LINE

