[package]
name = "rsp2"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]

[[bin]]
name = "rsp2"
path = "src/binary-shims/main.rs"

[[bin]]
name = "rsp2-shear-plot"
path = "src/binary-shims/shear-plot.rs"

[[bin]]
name = "rsp2-save-bands"
path = "src/binary-shims/save-bands.rs"

[[bin]]
name = "rsp2-bond-test"
path = "src/binary-shims/bond-test.rs"

[[bin]]
name = "rsp2-rerun-analysis"
path = "src/binary-shims/rerun-analysis.rs"

[dependencies]

# Workspace members
!!WORKSPACE-MEMBERS-AS-PATH-DEPS

# Deps of examples/ and tests/.
# Some of these could be dev-dependencies, however currently
#  none of them are due to rust-lang-nursery/rls#169
!!rand
!!serde_json
!!serde_yaml
!!log
!!fern
!!env-logger
!!clap
!!rsp2-kets
!!slice-of-array
!!ansi-term
!!itertools

# This is NOT a workspace anymore.
# I don't have time to debug the RLS.
