[package]
name = "rsp2-clap"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "Macros that suck less than clap_app"

[lib]
path = "lib.rs"

[dependencies]
!!clap
