[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "A safe(r) wrapper around the lammps C bindings."
!!LICENSE-GPL

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-structure
!!rsp2-array-types
!!lammps-sys

!!log
!!lazy-static
!!chrono
!!failure
!!slice-of-array

# FIXME: should be an optional dependency, but the crates script
#        has no way to do that.
!!mpi

[dev-dependencies]
!!rsp2-assert-close

[features]
!!NIGHTLY-FEATURE-LINE

# FIXME: Rename feature to "mpi" once mpi is properly an optional dep.
#
#        This dep with the underscored name exists to make it possible to disable mpi-related
#        features (to test conditional compilation) despite the current inadequacies
#        of the crates script
_mpi = ["lammps-sys/system-mpi"]
default = ["_mpi"]

