[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "Provides mathematical vector and matrix types used throughout rsp2."
!!LICENSE-PERMISSIVE

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-array-utils

!!serde
!!serde-derive
!!slice-of-array
!!num-traits

# FIXME make this dev-dependencies once rust-lang-nursery/rls#169 is fixed
!!rsp2-assert-close
# FIXME make this dev-dependencies once rust-lang-nursery/rls#169 is fixed
!!rand

[features]
!!NIGHTLY-FEATURE-LINE
