[package]
name = "rsp2-task-traits"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-tempdir
!!rsp2-fs-util

!!serde
!!serde-derive
!!serde-json
!!serde-yaml
!!error-chain
