[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "For parsing/writing dumb filetypes."

[lib]
path = "lib.rs"

[dependencies]
!!itertools
!!error-chain
!!vasp-poscar

!!rsp2-structure
!!rsp2-array-types
