[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "Macros that suck less than clap_app"
!!LICENSE-PERMISSIVE

[lib]
path = "lib.rs"

[dependencies]
!!clap

[features]
!!NIGHTLY-FEATURE-LINE
