[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "Where madness reigns eternal."

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-tasks-config

!!rsp2-lammps-wrap
!!rsp2-minimize
!!rsp2-structure
!!rsp2-structure-io
!!rsp2-structure-gen
!!rsp2-phonopy-io
!!rsp2-array-utils
!!rsp2-array-types
!!rsp2-soa-ops
!!rsp2-slice-math
!!rsp2-util-macros
!!rsp2-fs-util
!!rsp2-clap
!!rsp2-assert-close
!!rsp2-linalg

!!clap
!!slice-of-array
!!rsp2-kets
!!rand
!!log
!!failure
!!fern
!!extension-trait
!!itertools
!!lazy-static
!!ansi-term
!!rayon
!!serde
!!serde-derive
!!serde-json
!!serde-yaml
!!serde-ignored
!!path-abs
!!enum-map
!!frunk
!!shlex
!!indoc
!!lapacke
!!lapack-src

[features]
!!NIGHTLY-FEATURE-LINE
