[package]
name = "rsp2-array-types"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-array-utils

!!serde
!!serde-derive
!!slice-of-array

[dev-dependencies]
!!rsp2-assert-close
!!rand
