[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
!!LICENSE-PERMISSIVE
!!DEFAULT-EDITION

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-structure
!!rsp2-array-types
!!rsp2-fs-util

!!dftbplus-sys
!!failure
!!slice-of-array

[features]
!!NIGHTLY-FEATURE-LINE
