[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "Reads layer.yaml files, and is poorly named."

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-array-utils
!!rsp2-array-types
!!rsp2-structure

!!log
!!serde
!!serde-derive
!!serde-yaml
!!error-chain
