[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
!!LICENSE-GPL
description = "Embeds python modules used by rsp2 into the source code."

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-fs-util

!!include-dir
!!failure
!!log

[build-dependencies]
!!walkdir

[features]
!!NIGHTLY-FEATURE-LINE
