[package]
name = "rsp2-tasks"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "Where madness reigns eternal."

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-tasks-config

!!rsp2-lammps-wrap
!!rsp2-minimize
!!rsp2-structure
!!rsp2-structure-io
!!rsp2-structure-gen
!!rsp2-phonopy-io
!!rsp2-array-utils
!!rsp2-array-types
!!rsp2-slice-math
!!rsp2-util-macros
!!rsp2-fs-util
!!rsp2-clap

!!clap
!!slice-of-array
!!rsp2-kets
!!rand
!!log
!!fern
!!extension-trait
!!itertools
!!lazy-static
!!ansi-term
!!rayon
!!error-chain
!!serde
!!serde-derive
!!serde-json
!!serde-yaml
!!path-abs
!!enum-map
!!frunk
