[package]
!!CRATE-NAME-LINE
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "Code for computing the phonon dynamical matrix."
!!LICENSE-PERMISSIVE
!!DEFAULT-EDITION

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-array-types
!!rsp2-soa-ops
!!rsp2-structure
!!rsp2-newtype-indices
!!rsp2-sparse
!!rsp2-util-macros
!!rsp2-linalg
!!serde { features = ["derive"], optional = true }
!!slice-of-array
!!failure
!!num-traits
!!log
!!npyz { optional = true }

[dev-dependencies]
!!rand

[features]
!!NIGHTLY-FEATURE-LINE

npz = ["npyz"]

# FIXME
# Features for optional deps, because the implicit features defined by deps do not scale well.
# For now, THESE are what you should toggle in dependent crates.
#
# Once namespaced-features are stabilized, these features will be renamed after the deps.
# see https://github.com/rust-lang/cargo/issues/1286 (problem and proposal)
#     https://github.com/rust-lang/cargo/issues/5565 (tracking issue, of sorts)
serde-support = ["serde", "rsp2-array-types/serde-support"]
