[package]
name = "rsp2-tasks-config"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-minimize

!!log
!!serde
!!serde-derive
!!serde-yaml
!!serde-ignored
