[package]
name = "rsp2-tasks-config"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
description = "Stuff pulled out of rsp2-tasks because it takes too long to compile."

[lib]
path = "lib.rs"

[dependencies]
!!rsp2-minimize

!!log
!!serde
!!serde-derive
!!serde-yaml
!!serde-ignored
