[package]
name = "rsp2-linalg"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]

[lib]
path = "lib.rs"

[dependencies]
!!ndarray

[dependencies.ndarray-linalg]
version = "0.7"
features = ["openblas-system", "openblas-shared"]
default-features = false
