[package]
name = "sp2-lammps-wrap"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]

[lib]
path = "lib.rs"

[dependencies]
!!sp2-structure
!!lammps-sys

!!log
!!ndarray
!!slice-of-array
